controller_manager:
  ros__parameters:
    update_rate: 1000 #Hz

    ur5e_controller:
      type: velocity_controllers/JointGroupVelocityController

    mobile_controller:
      type: velocity_controllers/JointGroupVelocityController

    lift_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ur5e_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint


mobile_controller:
  ros__parameters:
    joints:
      - f_l_ew_joint
      - f_r_ew_joint
      - r_l_ew_joint
      - r_r_ew_joint
      - f_l_rotate_joint
      - f_r_rotate_joint
      - r_l_rotate_joint
      - r_r_rotate_joint

lift_controller:
  ros__parameters:
    joints:      
      - f_l_prismatic_joint
      - f_r_prismatic_joint
      - r_l_prismatic_joint
      - r_r_prismatic_joint
