float64 wheel_vel_fl
float64 wheel_vel_fr
float64 wheel_vel_rl
float64 wheel_vel_rr

float64 steering_vel_fl
float64 steering_vel_fr
float64 steering_vel_rl
float64 steering_vel_rr

float64 steering_pos_fl
float64 steering_pos_fr
float64 steering_pos_rl
float64 steering_pos_rr

float64 lift_vel_fl
float64 lift_vel_fr
float64 lift_vel_rl
float64 lift_vel_rr

float64 lift_pos_fl
float64 lift_pos_fr
float64 lift_pos_rl
float64 lift_pos_rr

float64 lift_trq_fl
float64 lift_trq_fr
float64 lift_trq_rl
float64 lift_trq_rr


